# action.yml
name: 'GitBit Intelligent Issue Bot'
description: 'Analyzes new issues to suggest labels, assignees, and related issues.'
author: 'LMLK-seal'

inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: pip install -r ${{ github.action_path }}/requirements.txt

    - name: Run GitBit Bot
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        # GITHUB_EVENT_PATH and GITHUB_REPOSITORY are automatically available
      run: python -m ${{ github.action_path }}/gitbit.main